### ISSUE TITLE
seasonplot: Multiplicative

### ISSUE THREAD

**Issue by wesleyburr** [iNZightVIT/iNZightTS#12]
If you attempt to use multiplicative seasonality on a series with negatives (e.g., monthly temperature), the error message that comes back from **seasonplot** is highly uniformative. There's no logical checks in **decomposition** to make sure that the series is suitable for multiplicative, so the logarithm gives NaN's, and **stl** dies.

**Suggest**: some logical checks at the start of decomposition() to give informative error messages. 

If I have time, I'll submit a pull request in a couple of weeks that fixes this issue.

**Comment by tmelliott** [comment]
Thanks @wesleyburr - we've been aware of this for some time, so if you find the time to submit a PR that'd be awesome!
