### ISSUE TITLE
Issues with the next release of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [iNZightVIT/iNZightTS#62]
Hi

We are preparing the next release of ggplot2 and our testing reveals an issue with iNZightTS. The issue is relatively minor and is due to the addition of new deprecation warnings in ggplot2 which makes your `expect_silent()` checks fail.

We plan to submit the next version of ggplot2 on May 31st

best
Thomas

**Comment by tmelliott** [comment]
Thanks @thomasp85 - will look into this. Keep up the great work!
